version: '3'
services:
  db:
    image: mysql:8
    container_name: graph-editor-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: graph_editor_db
      MYSQL_ROOT_PASSWORD: too_secret
      MYSQL_USER: admin
      MYSQL_PASSWORD: too_secret

  web:
    build: .
    image: graph_editor:1
    container_name: graph_editor
    ports:
      - 4000:4000
    env_file: ./app/.env
    volumes:
      - ./app:/usr/app
      - /usr/app/node_modules
    depends_on:
      - db
    command: "nodemon src/server.ts --watch 'src/**/*.ts' --exec 'ts-node'"
